### ISSUE TITLE
metrics.enable

### ISSUE THREAD

**Issue by AnthonyAMC** [fuzzyblocks/AnimalGuard#2]
Simply removing metrics.enable should lift the moderation of AnimalGuard on DBO. When you have that statement, it tells metrics to turn on... regardless of what the end user wants. You've basically taken that choice away from users.

**Comment by Velltho** [comment]
Fixed in 3eab6944b4862efa55ebeb7ccebc5b53828209bb

Metrics should now respect the end user's decision
